# Change these first
owner: MadeMediaCorp # Your GitHub organization or username, where this repository lives
repo: system-status # The name of this repository

sites:
  - name: Corpo Site
    url: https://mademedia.tech

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  publish: true
  cname: status.onboardapp.co
  logoUrl: https://mademedia.tech/img/favicon144.png
  name: Made Media
  introTitle: "**Made Media** provides a powerful suite of tools & software"
  introMessage: Find out about upcoming maintenence work, as well as any issues affecting our services.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"
