owner: MadeMediaCorp
repo: system-status

sites:
  - name: Mademedia Website
    url: https://mademedia.tech
  - name: Onboard Website
    url: https://onboardapp.co
  - name: Self-Complete
    url: https://complete.onboardapp.co/en.html
    expectedStatusCodes: 
      - 404
    __dangerous__body_down_if_text_missing: "Unfortunately this link has expired"
  - name: App
    url: $RELEASES_JSON
    __dangerous__body_down_if_text_missing: "releases"
  - name: Portal
    url: $PORTAL_JSON
  - name: API
    url: $API_JSON

status-website:
  theme: dark
  cname: status.onboardapp.co
  favicon: https://mademedia.tech/img/favicon.png
  logoUrl: https://mademedia.tech/img/favicon144.png
  name: Made Media
  introTitle: "Find out about upcoming maintenence work, as well as any issues affecting our services."
  navbar:
    - title: Contact
      href: https://mademedia.tech/contact

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"

i18n:
  pastScheduledMaintenance: Past Manually Created Incidents
  scheduledMaintenance: Manually Created Incidents